Added documentation for Koala OAuth2
svsticky/undead-mongoose pull request #34
Opened 2022-10-19 21:42 UTC by TobiasDeBruijn

This PR adds to the README to describe setting up Koala OAuth2

2022-10-27 09:41 UTC, JustNireon requested changes

2022-10-27 09:41 UTC, JustNireon commented on README.md
> +INSERT INTO public.oauth_applications(name, uid, secret, redirect_uri) VALUES ('mongoose', 'example_id', 'example_secret', 'http://localhost:8000/oidc/callback/');
Even though this is not wrong it does not limit the scopes and a preferable way would probably.
running this command in a nix-shell of koala
`bundle exec rake "doorkeeper:create[undead Mongoose, http://localhost:8000/oidc/callback/, openid profile email member-read]"`
Granting undead_mongoose access to koala should not be required and probably a bad idea

2022-11-22 19:01 UTC, Phavion requested changes
To enable oauth for koala locally, you should go to koala.rails.local:3000/api/oauth/applications and create a new application with {{ canonical_hostname }}/oidc/callback/ as the callback url. Ensure scopes 'openid member-read email profile' are present. Also ensure to copy the application_id and secret and put them in your .env file. Make sure that the endpoints are correct. The ones in sample.env should suffice.

2023-09-28 19:20 UTC, PrinceMordred approved these changes
lgtm :)

2023-09-28 19:20 UTC, merged