feat: ideal topups
svsticky/undead-mongoose pull request #65
Opened 2024-12-16 20:01 UTC by stickyPiston

closes #60

2024-12-29 20:37 UTC, TobiasDeBruijn commented
Important note: We used to have one Mollie API key, we now have multiple:
- Koala
- Pretix
- Mongoose
I think this will have to be changed in SadServer, but Mongoose should use the Mongoose balance in Mollie, and use the appropriate API key for it (from Mollie)

2024-12-29 20:56 UTC, stickyPiston commented
What do you mean with mongoose balance in "but Mongoose should use the Mongoose balance in Mollie" exactly?

2024-12-29 22:25 UTC, TobiasDeBruijn commented
So within our Mollie account we used to have just one 'Balance', which is a thing our users pay into. So if you pay your Koala activities, the money goes into that balance. Mollie then pays us that balance weekly (or whatever we configure).

This poses a problem for us treasurers. Every monday we need to split out this balance into it's separate components, currently only Pretix and Koala. However, recently I introduced two new balances: Pretix and Mongoose. This way, I get three seperate pay-outs every week, one for each product. This means I don't have to split it out manually anymore.

For mongoose (or Pretix), the only thing that changes is the Mollie API key used.

2025-01-02 14:52 UTC, TobiasDeBruijn requested changes

2025-01-02 14:52 UTC, TobiasDeBruijn commented on admin_board_view/templates/user_home.html
> +            <small id="feeHelp" class="form-text text-muted">Plus &euro;0.39 transaction fee.</small>
This should be configurable, the 0.39

2025-01-02 14:52 UTC, TobiasDeBruijn commented on admin_board_view/views.py
> +                        '"",5007,Mongoose transaction fee 0.39 x 1,21,0.39,TRX\n'
See above

2025-01-02 14:52 UTC, TobiasDeBruijn commented on admin_board_view/views.py
> +                        '"",5007,Mongoose transaction fee 0.39 x 1,21,0.39,TRX\n'
The TRX fees should be summed up too, so instead of two rows for 5007, it should be one saying x2 and value 0,78

2025-01-02 14:52 UTC, TobiasDeBruijn commented
> Ahhh alright, the mollie api client only receives the api key that is configured in the .env file and does nothing with balances and whatnot, so i reckon that should be fine.

Yep that is fine! It's something to consider when deploying, though. The secrets probably still need to be created

2025-01-02 15:26 UTC, stickyPiston commented on admin_board_view/templates/user_home.html
> +            <small id="feeHelp" class="form-text text-muted">Plus &euro;0.39 transaction fee.</small>
oh yeah you're right, I missed that one!

2025-01-02 16:14 UTC, TobiasDeBruijn approved these changes

2025-01-02 18:15 UTC, merged